dist: xenial
language: python
python:
  - "3.8.5"
notifications:
  email:
    - powen@renci.org
services:
  - docker
install:
  - pip install tox httpx
  - mkdir logs
env:
  global:
    - PYTHONPATH=$PWD
script:
  - tox

