contact:
  email: patrick@covar.com
  name: Patrick Wang
  x-id: https://github.com/patrickkwang
  x-role: responsible developer
description: 'ARAGORN: Performs a query operation which compiles data from numerous ARAGORN ranking agent services.'
servers:
- description: Default server
  url: https://aragorn.renci.org
termsOfService: http://robokop.renci.org:7055/tos?service_long=ARAGORN&provider_long=RENCI
title: ARAGORN
tags:
- name: translator
- name: ARA
x-translator:
  component: ARA
  team:
  - Ranking Agent
x-trapi:
  version: 1.2.0.2
  operations:
  - lookup
  - enrich_results
  - connect_knodes
  - score