version: 1
formatters: 
  default: 
    format: "[%(asctime)s: %(levelname)s/%(name)s(%(processName)s)]: %(message)s"
handlers: 
  console: 
    class: logging.StreamHandler
    level: INFO
    formatter: default
  file: 
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: "aragorn.log"
    mode: a
    encoding: utf-8
    maxBytes: 1000000
    backupCount: 9
loggers:
  src.server:
      level: INFO
      handlers:
        - console
        - file
  src.service_aggregator:
      level: INFO
      handlers:
        - console
        - file
incremental: false
disable_existing_loggers: false